### ISSUE TITLE
Hiragana for Katakana names not scraped properly

### ISSUE THREAD

**Issue by hopto-dot** [kaanium/VNDB-Names-for-Yomitan#1]
Example:
```
[
    "シュガー",
    "すがr",
    "",
    "",
    0,
    [
      "Sugar"
    ],
    87703,
    ""
  ],
  ```

Specifically「すがr」should be 「しゅがー」

**Comment by kaanium** [comment]
Yeah, I generated their readings using the English definitions, but I could just look up kana-only words and turn them into hiragana for reading instead, though this won't fix the first name kanji, second name kana type of cases. Or just remove the kana names all together

**Comment by kaanium** [comment]
I fixed kana-only names, but there isn't really any way for me to fix everything, because VNDB doesn't have character name readings, just how they are written, so I have to generate their reading myself. Which means there are entries like suspicious person - すｓぴしおうｓぺｒそｎ which should be fixed by hand.

**Comment by kaanium** [comment]
I decided to remove any reading that had English characters in it, this and the previous version should fix MOST of these broken entries.
